/* This file is generated by tools/generate-document-presentation.mjs. Do not edit. */
import type { DocumentLocale } from '../types.js'

export const DOCUMENT_TEMPLATE_IDS = [
  "openspec-proposal",
  "openspec-design",
  "workflow-tasks",
  "superpower-design",
  "architecture-decision-record",
  "openspec-delta-spec",
  "superpower-plan",
  "implementation-plan",
  "verification-report",
  "applied-spec"
] as const
export type DocumentTemplateId = (typeof DOCUMENT_TEMPLATE_IDS)[number]

export const DOCUMENT_WORKFLOW_STEP_IDS = [
  "open",
  "explore",
  "spec",
  "build",
  "verify",
  "ship",
  "archive"
] as const
export type DocumentWorkflowStepId = (typeof DOCUMENT_WORKFLOW_STEP_IDS)[number]

export interface DocumentTemplateDefinition {
  readonly kind: string
  readonly path: string
  readonly sections: readonly string[]
  readonly layout: readonly string[]
  readonly creation: 'missing-only'
}

export const DOCUMENT_PRESENTATION_REGISTRY = {
  "version": "v1",
  "templates": {
    "openspec-proposal": {
      "kind": "proposal",
      "path": "openspec/changes/{change}/proposal.md",
      "sections": [
        "title",
        "why",
        "whyPrompt",
        "whatChanges",
        "whatChangesPrompt",
        "capabilities",
        "newCapabilities",
        "newCapabilitiesPrompt",
        "modifiedCapabilities",
        "modifiedCapabilitiesPrompt",
        "impact",
        "impactPrompt"
      ],
      "layout": [
        "h1:title",
        "h2:why",
        "quote:whyPrompt",
        "h2:whatChanges",
        "quote:whatChangesPrompt",
        "h2:capabilities",
        "h3:newCapabilities",
        "quote:newCapabilitiesPrompt",
        "h3:modifiedCapabilities",
        "quote:modifiedCapabilitiesPrompt",
        "h2:impact",
        "quote:impactPrompt"
      ],
      "creation": "missing-only"
    },
    "openspec-design": {
      "kind": "openspec-design",
      "path": "openspec/changes/{change}/design.md",
      "sections": [
        "title",
        "hypothesis",
        "hypothesisPrompt",
        "risks",
        "questions"
      ],
      "layout": [
        "h1:title",
        "h2:hypothesis",
        "quote:hypothesisPrompt",
        "h2:risks",
        "h2:questions"
      ],
      "creation": "missing-only"
    },
    "workflow-tasks": {
      "kind": "tasks",
      "path": "openspec/changes/{change}/tasks.md",
      "sections": [
        "title",
        "taskPrompt"
      ],
      "layout": [
        "h1:title",
        "workflow-steps:taskPrompt"
      ],
      "creation": "missing-only"
    },
    "superpower-design": {
      "kind": "superpower-design",
      "path": "docs/superpowers/specs/{change}-design.md",
      "sections": [
        "title",
        "context",
        "decision",
        "alternatives",
        "risks"
      ],
      "layout": [
        "h1:title",
        "h2:context",
        "prompt-placeholder:context",
        "h2:decision",
        "prompt-placeholder:decision",
        "h2:alternatives",
        "prompt-placeholder:alternatives",
        "h2:risks",
        "prompt-placeholder:risks"
      ],
      "creation": "missing-only"
    },
    "architecture-decision-record": {
      "kind": "adr",
      "path": "docs/adr/{change}.md",
      "sections": [
        "title",
        "context",
        "decision",
        "alternatives",
        "consequences"
      ],
      "layout": [
        "h1:title",
        "h2:context",
        "prompt-placeholder:context",
        "h2:decision",
        "prompt-placeholder:decision",
        "h2:alternatives",
        "prompt-placeholder:alternatives",
        "h2:consequences",
        "prompt-placeholder:consequences"
      ],
      "creation": "missing-only"
    },
    "openspec-delta-spec": {
      "kind": "delta-spec",
      "path": "openspec/changes/{change}/specs/{capability}/spec.md",
      "sections": [
        "title",
        "operations",
        "requirement",
        "prompt",
        "scenario"
      ],
      "layout": [
        "h1:title",
        "h2:operations",
        "h3-pending:requirement",
        "text:prompt",
        "h4-pending:scenario",
        "scenario-pending"
      ],
      "creation": "missing-only"
    },
    "superpower-plan": {
      "kind": "superpower-plan",
      "path": "docs/superpowers/plans/{change}.md",
      "sections": [
        "title",
        "tasks",
        "verification",
        "rollback"
      ],
      "layout": [
        "frontmatter",
        "h1:title",
        "h2:tasks",
        "task-pending",
        "h2:verification",
        "h2:rollback"
      ],
      "creation": "missing-only"
    },
    "implementation-plan": {
      "kind": "plan",
      "path": "docs/superpowers/plans/{change}.md",
      "sections": [
        "title",
        "tasks",
        "verification",
        "rollback"
      ],
      "layout": [
        "frontmatter",
        "h1:title",
        "h2:tasks",
        "task-pending",
        "h2:verification",
        "h2:rollback"
      ],
      "creation": "missing-only"
    },
    "verification-report": {
      "kind": "verification-report",
      "path": "docs/superpowers/reports/{change}-verify.md",
      "sections": [
        "title",
        "scope",
        "commands",
        "results",
        "failures",
        "risks"
      ],
      "layout": [
        "h1:title",
        "h2:scope",
        "prompt-placeholder:scope",
        "h2:commands",
        "prompt-placeholder:commands",
        "h2:results",
        "prompt-placeholder:results",
        "h2:failures",
        "prompt-placeholder:failures",
        "h2:risks",
        "prompt-placeholder:risks"
      ],
      "creation": "missing-only"
    },
    "applied-spec": {
      "kind": "applied-spec",
      "path": "openspec/changes/{change}/applied-spec.md",
      "sections": [
        "title",
        "summary",
        "requirements",
        "evidence"
      ],
      "layout": [
        "h1:title",
        "h2:summary",
        "prompt-placeholder:summary",
        "h2:requirements",
        "prompt-placeholder:requirements",
        "h2:evidence",
        "prompt-placeholder:evidence"
      ],
      "creation": "missing-only"
    }
  }
} as const satisfies {
  readonly version: 'v1'
  readonly templates: Readonly<Record<DocumentTemplateId, DocumentTemplateDefinition>>
}

type LocaleTemplate = Readonly<Record<string, string>>
export type DocumentLocaleCatalog = Readonly<Record<DocumentTemplateId, LocaleTemplate>>

export const DOCUMENT_LOCALE_CATALOGS = {
  "zh-CN": {
    "openspec-proposal": {
      "title": "提案",
      "why": "Why",
      "whyPrompt": "[待填写:open] 用中文说明问题、机会和现在必须改变的原因。",
      "whatChanges": "What Changes",
      "whatChangesPrompt": "[待填写:open] 用中文列出具体变化、范围、非目标和可验证结果。",
      "capabilities": "Capabilities",
      "newCapabilities": "New Capabilities",
      "newCapabilitiesPrompt": "[待填写:open] 列出新增 capability；没有则写“无”。",
      "modifiedCapabilities": "Modified Capabilities",
      "modifiedCapabilitiesPrompt": "[待填写:open] 列出 requirement 会变化的现有 capability；没有则写“无”。",
      "impact": "Impact",
      "impactPrompt": "[待填写:open] 用中文说明受影响的代码、契约、依赖、兼容和系统边界。"
    },
    "openspec-design": {
      "title": "设计",
      "hypothesis": "初始假设",
      "hypothesisPrompt": "[待填写:open] 记录初始架构或交互假设；Explore 用证据和决策替换本提示。",
      "risks": "风险",
      "questions": "待验证问题"
    },
    "workflow-tasks": {
      "title": "任务",
      "taskPrompt": "将本阶段目标拆成可验证任务。"
    },
    "superpower-design": {
      "title": "技术设计",
      "context": "背景",
      "decision": "决策",
      "alternatives": "备选方案",
      "risks": "风险"
    },
    "architecture-decision-record": {
      "title": "架构决策记录",
      "context": "背景",
      "decision": "决策",
      "alternatives": "备选方案",
      "consequences": "后果"
    },
    "openspec-delta-spec": {
      "title": "OpenSpec 增量规格",
      "operations": "ADDED Requirements",
      "requirement": "Requirement",
      "scenario": "Scenario",
      "prompt": "[待填写:spec] 使用中文编写需求与场景；每条 requirement 正文须含英文 SHALL 或 MUST（如「系统 SHALL …」，中文「必须」不被 OpenSpec strict validate 接受）；保留 OpenSpec 机器操作词。"
    },
    "superpower-plan": {
      "title": "实施计划",
      "tasks": "任务",
      "verification": "验证",
      "rollback": "回滚"
    },
    "implementation-plan": {
      "title": "实施计划",
      "tasks": "任务",
      "verification": "验证",
      "rollback": "回滚"
    },
    "verification-report": {
      "title": "验证报告",
      "scope": "验证范围",
      "commands": "执行命令",
      "results": "结果",
      "failures": "失败与阻塞",
      "risks": "剩余风险"
    },
    "applied-spec": {
      "title": "已应用规格",
      "summary": "变更摘要",
      "requirements": "已应用需求",
      "evidence": "交付证据"
    }
  },
  "en": {
    "openspec-proposal": {
      "title": "Proposal",
      "why": "Why",
      "whyPrompt": "[pending:open] Explain the problem or opportunity and why it matters now.",
      "whatChanges": "What Changes",
      "whatChangesPrompt": "[pending:open] List concrete changes, scope, non-goals, and verifiable outcomes.",
      "capabilities": "Capabilities",
      "newCapabilities": "New Capabilities",
      "newCapabilitiesPrompt": "[pending:open] List new capabilities, or state None.",
      "modifiedCapabilities": "Modified Capabilities",
      "modifiedCapabilitiesPrompt": "[pending:open] List existing capabilities with requirement changes, or state None.",
      "impact": "Impact",
      "impactPrompt": "[pending:open] Describe affected code, contracts, dependencies, compatibility, and systems."
    },
    "openspec-design": {
      "title": "Design",
      "hypothesis": "Initial hypothesis",
      "hypothesisPrompt": "[pending:open] Capture the initial architecture or interaction hypothesis. Explore replaces this prompt with evidence and decisions.",
      "risks": "Risks",
      "questions": "Questions to validate"
    },
    "workflow-tasks": {
      "title": "Tasks",
      "taskPrompt": "Break this phase goal into verifiable tasks."
    },
    "superpower-design": {
      "title": "Technical design",
      "context": "Context",
      "decision": "Decision",
      "alternatives": "Alternatives",
      "risks": "Risks"
    },
    "architecture-decision-record": {
      "title": "Architecture decision record",
      "context": "Context",
      "decision": "Decision",
      "alternatives": "Alternatives",
      "consequences": "Consequences"
    },
    "openspec-delta-spec": {
      "title": "OpenSpec delta specification",
      "operations": "ADDED Requirements",
      "requirement": "Requirement",
      "scenario": "Scenario",
      "prompt": "[pending:spec] Write the requirement and scenarios; every requirement body needs SHALL or MUST (OpenSpec strict validation rejects it otherwise), and keep OpenSpec machine tokens."
    },
    "superpower-plan": {
      "title": "Implementation plan",
      "tasks": "Tasks",
      "verification": "Verification",
      "rollback": "Rollback"
    },
    "implementation-plan": {
      "title": "Implementation plan",
      "tasks": "Tasks",
      "verification": "Verification",
      "rollback": "Rollback"
    },
    "verification-report": {
      "title": "Verification report",
      "scope": "Scope",
      "commands": "Commands run",
      "results": "Results",
      "failures": "Failures and blockers",
      "risks": "Residual risks"
    },
    "applied-spec": {
      "title": "Applied specification",
      "summary": "Change summary",
      "requirements": "Applied requirements",
      "evidence": "Delivery evidence"
    }
  }
} as const satisfies Readonly<
  Record<DocumentLocale, DocumentLocaleCatalog>
>

export const DOCUMENT_WORKFLOW_STEP_LABELS = {
  "zh-CN": {
    "open": "立项",
    "explore": "调研",
    "spec": "规格",
    "build": "实现",
    "verify": "验证",
    "ship": "交付",
    "archive": "归档"
  },
  "en": {
    "open": "Open",
    "explore": "Explore",
    "spec": "Spec",
    "build": "Build",
    "verify": "Verify",
    "ship": "Ship",
    "archive": "Archive"
  }
} as const satisfies Readonly<
  Record<DocumentLocale, Readonly<Record<DocumentWorkflowStepId, string>>>
>
