export * from './document-presentation-registry.js'
export * from './document-template-renderer.js'
export { recordDocument } from './document-recording.js'
export type { RecordDocumentInput } from './document-recording.js'
export { canonicalDocumentPaths, documentPathTemplates } from './document-paths.js'
export { autoRegisterDocuments } from './auto-register.js'
export type { AutoRegisterDeps, AutoRegisterInput, AutoRegisterOutcome } from './auto-register.js'
